### ISSUE TITLE
All files do not contain wordlists

### ISSUE THREAD

**Issue by jamesbrinekasada** [six2dez/OneListForAll#5]
All files have been replaced with the below, in place of the wordlists.
version...
oid sha256:...
size: ...

**Comment by six2dez** [comment]
WTF thanks for pointing this out, [git lfs](https://git-lfs.github.com/) has f*cked up everything. I will fix asap.

**Comment by riramar** [comment]
Same here.

**Comment by six2dez** [comment]
It's already fixed, download it again

**Comment by indigo-sadland** [comment]
Release archives still have the same problem 🙃

**Comment by six2dez** [comment]
New release with fixes https://github.com/six2dez/OneListForAll/releases/tag/v2.4.1 :) Thanks!
