### ISSUE TITLE
v2.4.1 release does not include standalone wordlists

### ISSUE THREAD

**Issue by lauritzh** [six2dez/OneListForAll#6]
Hey there!

I just noticed that you recently tagged new releases - thank you very much for your efforts! 

Unfortunately the recent releases do not include the standalone wordlists such as `onelistforall.txt`, `onelistforallshort.txt`, ... as dedicated assets (like it was the case for v2.3 for instance). 

Is this intended?

Best regards,
Lauritz

**Comment by six2dez** [comment]
Yes! It's because of a size limit on GitHub, you have to build them by yourself running the script, sorry! Anyway I released https://github.com/six2dez/OneListForAll/releases/tag/v2.4.1.1 which includes `onelistforallshort.txt` :)

**Comment by lauritzh** [comment]
Thank you very much!
